#!/bin/bash
invalid_input(){
    echo "Invalid Input '$REPLY' " >&2
    exit 1
}

read -p "Enter any single value to validate > "

#empty input
[[ -z $REPLY ]] && invalid_input

#many items in input
(( $(echo $REPLY |wc -w) > 1)) && invalid_input

# valid file name with regex
if [[$REPLY =~ [-[:alnum:]\._]+$]];then
    echo "'$REPLY' is a valid filename."
    if [[-e $REPLY]]; then 
        echo "And file '$REPLY' exists."
    else 
        echo "But, file '$REPLY' does not exist."
    fi
else
    echo "The string '$REPLY' is not a valid filename."
fi

#floating point number
if [[$REPLY =~ ^-?[[:digit:]]*\.[[:digit:]]+$]];then
    echo "'$REPLY' is a floating point number."
else 
    echo "'$REPLY' is not a floating point number."
fi

#input an integer
  
if [[$REPLY =~ ^-?[[:digit:]]+$]];then  
    echo "'$REPLY' is an integer."
else
    echo "'$REPLY' is not an integer."
fi


