#!/bin/bash

#menu driven sys info page

clear
echo "
Please select an option:

1. Show system info
2. Show Disk Space
3. Show Home Directory Utlization
0. Exit
"

read -p "Enter the selection (0-3) > "

if [[ $REPLY =~ ^[0-3]$ ]];then
    if [[ $REPLY == 0 ]]; then
        echo "Exiting"
        exit
    fi
    if [[ $REPLY == 1 ]];then 
        echo "Host : $HOSTNAME"
        uptime
        exit
    fi
    if [[ $REPLY == 2 ]];then
        df -h
        exit
    fi
    if [[ $REPLY == 3 ]]; then
        if [[ $(id -u) -eq 0 ]];then
            echo "All Users Home Space"
            du -sh /home/*
        else
            echo "Home Space for ($USER)"
            du -sh $HOME
        fi
        exit
    fi
else
    echo "Invalid Entry " >&2
    exit 1
fi
