#!/bin/bash

# read fields from a file

FILE=/etc/passwd

read -p "Enter the user name for which info is needed - > " user_name

file_info=$(grep "^$user_name:" $FILE)

if [ -n "$file_info" ] ; then
    IFS=":" read user pw uid gid name home shell <<< "$file_info"
    echo "User is $user"
    echo "GID is $gid"
    echo "UID is $uid"
    echo "fullname is $name"
    echo "Home Directory is $dir"
    echo "Shell is $shell"
else 
    echo "No such user '$user_name'" >&2
    exit 1
fi


