#!/bin/bash

# timed out secret password

if read -t 10 -sp "Enter a secret passphrase -> " secret_pass ; then
    echo -e "\nSecret Passphrase = '$secret_pass'"
else 
    echo -e "\nInput timed out " >&2
    exit 1
fi

