#!/bin/bash

ANSWER=maybe

if [ -z "$ANSWER" ] ; then
	echo "There is no answer" >$2
	exit 1
fi

if [ "$ANSWER" == "yes" ]; then
	echo "the answer is YES."

elif [ "$ANSWER" == "no" ]; then
	echo "the answer is NO."

elif [ "$ANSWER" == "maybe" ]; then
	echo "the answer is MAYBE."

else
	echo "The answer is not known."
fi

